PrestaShop/php-dev-tools

src/Command/AbstractCommand.php
```
$ vendor/bin/prestashop-coding-standards cs-fixer:init
php_cs.dist already exists in destination folder /home/thomas/Documents/github/ps_checkpayment. Overwrite? [y/N] y
File "php_cs.dist" copied to "./.php_cs.dist"
prettyci.composer.json already exists in destination folder /home/thomas/Documents/github/ps_checkpayment. Overwrite? [y/N] y
File "prettyci.composer.json" copied to "./.prettyci.composer.json"
```
=> Fix php doc and make overwrite message more explicit

templates/phpstan/bootstrap.php
When integrating header-stamp in this project, php-parser has been included at the same time, breaking all run of phpstan.
This was caused by the php-parser lib from the module loaded at the end which took the first position in the autoloaders list. This change allows PhpStan PHAR to get the priority.
=> Update order of php-parser loading

phpstan/bootstrap.php
When using PHPStan with PS 1.6 and below, the constant `_PS_VERSION_` is declared as undefined. This PR defines it from the data available in the install/ folder.
This PR also fixes an issue with Smarty with is not handled by the PrestaShop autoloader, thus never found.
=> Improve declaration of _PS_VERSION_ constant

README.md, phpstan/ps-module-extension.neon, src/ErrorFormatter/GithubErrorFormatter.php
This PR adds an error formatter for PHPStan. It makes errors displayed in the pull-request diff as annotations, which facilitate access to the report and may avoid redundant checks.
=> Add an error formatter for GitHub actions annotations

phpstan/ps-module-extension.neon
PHPStan has elvoved and requires our configuration file to be updated:
The changes follows the new documentation
=> Use bootstrapFiles in phpstan config

phpstan/ps-module-extension.neon
to let phpstan understan that this constant can vary.
For example, if a module logs errors depending on the dev_mode
```php
if (_PS_MODE_DEV_) {
Logger::AddLog(' blabla ' . $exception->getMessage());
}
```
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. Every detail helps: What are you changing? Why?
| Type?         | bug fix / improvement / new feature / refacto
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes {paste the issue here}.
| How to test?  | Please indicate how to best verify that this PR is correct.
=> phpstan config : add  _PS_MODE_DEV_ to dynamicConstantNames

phpstan/bootstrap.php
As previous check, may help with configuration.
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Abort bootstrap if _PS_ROOT_DIR_ is incorrect
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | nop
| How to test?  | run a phpstan with a wrong _PS_ROOT_DIR_ env variable.
=> Abort bootstrap if _PS_ROOT_DIR_ is incorrect

src/Command/CsFixerInitCommand.php, src/Command/PhpStanInitCommand.php
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | This correct a type error when running the phpstan init command
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Please indicate how to best verify that this PR is correct.
```
PHP Fatal error:  Uncaught TypeError: Return value of "PrestaShop\CodingStandards\Command\PhpStanInitCommand::execute()" must be of the type int, "null" returned. in vendor/symfony/console/Command/Command.php:258
Stack trace:
#0 vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 …
```
=> Correct return value for init command

phpstan/stubs/Module.stub
| Description?      | Fix one error reported by phpstan with old versions of PrestaShop about Module::getInstanceByName. It has been fixed on 1.7.7.0 by @Matt75 on https://github.com/PrestaShop/PrestaShop/commit/9a8144a15d21e3fdcde3e2a703de3339be6e8295 but still appears on previous versions.
| How to test?      | Run PHPStan on PS < 1.7.7.0 with a module testing the result of Module::getInstanceByName
| Possible impacts? | /
```
------ ------------------------------------------------------------------ 
Line   controllers/admin/AdminPsfacebookModuleController.php …
```
=> Add stub for Module::getInstanceByName always returning true

.github/workflows/php.yml
| Description?      | If we rely on `prestashop/github-action-php-lint@master` the php version is frozen and this adds a layer of maintainance while the equivalent GitHub Action is not so big.<br/><br/>Also this repository should not depend on a PrestaShopCorp repository as it belongs to the OSS organization.
| Fixed ticket?     | 
| How to test?      | 
| Possible impacts? |
=> Update PHP Syntax linter github action to use standard GA instead of prestashop/github-action-php-lint@master

.github/workflows/php.yml
| Description?      | If we rely on `prestashopcorp/github-action-php-cs-fixer@master` the php version is frozen and this adds a layer of maintainance while the equivalent GitHub Action is not so big.<br/><br/>Also this repository should not depend on a PrestaShopCorp repository as it belongs to the OSS organization.
| Fixed ticket?     | 
| How to test?      | 
| Possible impacts? |
=> Update PHP CS Fixer github action to use standard GA instead of prestashopcorp/github-action-php-cs-fixer

composer.json
| Description?      | Seen with https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5537, the version 2.18.3 of php-cs-fixer breaks our pipeline. Let's avoid this version.
| Type?             | bug fix
| Fixed ticket?     | Fixes all PHP pipelines
| How to test?      | /
| Possible impacts? | None
=> Avoid specific version of php-cs-fixer

templates/phpstan/phpstan.neon
| Description?      |  fix bad default in phpstan.neon
| Type?             | bug fix
| Deprecations?     |  no
| Fixed ticket?     | Fixes #51 
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | ? probably none, because I changed the template, not the filename.
This may help to test : (grabed from my history) (not retested) :
```shell
git clone https://github.com/PrestaShop/blockreassurance.git --depth 1
cd blockreassurance
composer install --dev
wget https://github.com/phpstan/phpstan/releases/download/0.12.83/phpstan.phar
chmod +x phpstan.phar
php vendor/bin/prestashop-coding-standards phpstan:init …
```
=> Fix wrong filepath

.github/workflows/php.yml, bin/prestashop-coding-standards, composer.json, composer.lock, src/Command/AbstractCommand.php, src/Command/CsFixerInitCommand.php, src/Command/PhpStanInitCommand.php, src/CsFixer/Config.php, tests/modules_samples/constant_check/composer.json
| Description?      | Use latest version of header-stamp and use PHP 7.2.5+
=> Update dependencies to be compliant with PHP 7.2.5+

phpstan/stubs/Module.stub
| Description?      | Stubs files are no analyzed: https://phpstan.org/user-guide/stub-files#:~:text=Stub%20files%20are%20analysed%20independently,the%20problem%20of%20optional%20dependencies. And Abstract class can't return an instance of parent class because it's not defined yet.
| Type?             | bug fix
=> Fix stub, ModuleCore can't return Module instance

phpstan/bootstrap.php
replacement for #54 (same but finished and rebase on fresh master branch).
| Description?      | Avoid undefined constants : makes phpstan tests fail on CI
| Type?             | bug fix 
| BC breaks?        |  no
| Fixed ticket?     | #53 
| How to test?      | run the analyse , ?(use php 7.4)
| Possible impacts? |  may hide problems inside Prestashop, but this is not to test Prestashop.
=> defines _THEME_NAME_ & __PS_BASE_URI__ early to avoid warnings.

README.md, composer.json, composer.lock
| Description?      | Add autoindex v2 to php-dev-tools libraries
| Type?             | new feature
| How to test?      | /
| Possible impacts? | /
=> Add autoindex lib to php-dev-tools (v4 branch)

README.md, composer.json, composer.lock
| Description?      | Add autoindex to php-dev-tools libraries. This library is useful for modules that need to avoid access to their folders.
| Type?             | new feature
| How to test?      | /
| Possible impacts? | /
=> Add autoindex lib to php-dev-tools (v3 branch)

README.md
| Description?      | Just a minor change in the `README.md` that had one error about `php-cs-fixer` being run with `php` in front, that is wrong.
| Type?             | bug fix 
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | 
| How to test?      | Agree/disagree that that feature is now correctly documented
| Possible impacts? | none
=> Remove php in front of vendor/bin/php-cs-fixer fix, since that is wrong

composer.json, composer.lock
| Description?      | Adding Symfony 6 components to increase compatibility with projects running with latest version. The validator has been upgraded to it, the next step is to require php-dev-tools to reuse the PHP-CS-Fixer configuration file to stay up-to-date.
| How to test?      | Requiring this branch via composer works with SF6, while the lastest release does not.
| Possible impacts? | No impact expected for running projects. The oldest version available will still be required.
=> Allow v6.x of Symfony components to be loaded

phpstan/ps-module-extension.neon
| Description?      | This PR allows developer to load our configuration files from any folder, not only the vendor/ at the root of the module.
| Sponsor company   | /
| How to test?      | No change for existing users, new ones can require the dependency a subfolder and still be able to call phpstan.
=> Load bootstrap.php file with a relative path, removing an hardcoded path to the root vendor folder

.github/workflows/phpstan.yml, README.md, composer.json, composer.lock, tests/modules_samples/constant_check/composer.json, tests/modules_samples/constant_check/composer.lock, tests/modules_samples/constant_check/run.sh
| Description?      | Dependencies and their versions have been reported to sometimes trigger issues on projects relying on `php-dev-tools` . This PRs upgrades the way tools are being linked so module developers have a total control on their project dependencies. 
| BC breaks?        | Yes, each tools must now be manually required
| Sponsor company   | @PrestaShopCorp
| How to test?      | /
=> Suggest dependencies instead of requiring them
